# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.disksize.size = '100GB'

  config.vm.synced_folder '../build/Linux',  "/vagrant/scripts"
  config.vm.synced_folder '../build/config', "/vagrant/config"

  host_memory = `sysctl -n hw.memsize`.to_i / 1024 / 1024
  host_cpus = `sysctl -n hw.physicalcpu`.to_i 
  client_memory = [host_memory / 2, 80192].min

  config.vm.provider "virtualbox" do |vb|
    vb.memory = client_memory.to_s
    vb.cpus = host_cpus # use all available
  end

  config.vm.provision "shell", path: "provision/010_install_dependencies.sh"
  config.vm.provision "shell", path: "provision/020_install_ndk.sh", privileged: false
  config.vm.provision "shell", path: "provision/030_define_build_folders.sh", privileged: false
end
