name: Build Android SDK

on:
  pull_request:
    branches:
      - master

jobs:

  build-swift-android-sdk:
    runs-on: [self-hosted, Linux, x64, Ubuntu]
    
    steps:
    - name: Cleanup
      run: sudo rm -rf ./*
    - uses: actions/checkout@v1
    - name: Build sdk with docker
      run: sudo ./build-docker tag:swift-6.2.1-RELEASE ./android-sdk
    - uses: actions/upload-artifact@v4
      with:
        name: swift-6.2.1-RELEASE_android.artifactbundle.tar.gz
        path: ./android-sdk/products/swift-6.2.1-RELEASE_android.artifactbundle.tar.gz
