name: Build Android SDK

on:
  pull_request:
    branches:
      - master

jobs:

  build-android-sdk:
    runs-on: [self-hosted, Linux, x64, Ubuntu]
    
    steps:
    - uses: actions/checkout@v1
    - name: Build sdk with docker
      run: ./build-docker tag:swift-6.2-RELEASE ./android-sdk
